name: Build Devcontainer Image

on:
  workflow_dispatch:
    inputs:
      folder:
        description: Name of folder containing the devcontainer
        required: true
        default: ".github"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: "latest"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{ github.event.inputs.folder }}
          imageName: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.folder }}:latest
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.folder }}:latest
          push: always
