name: Push Devcontainer Image

on:
  workflow_dispatch:
    inputs:
      template:
        description: Name of folder containing the devcontainer
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Push image for '${{ github.event.inputs.template }}'
        uses: ./.github/actions/push-image
        with:
          template: "${{ github.event.inputs.template }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
