name: "Release Dev Container Templates & Generate Documentation"

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Publish Templates
        uses: devcontainers/action@v1
        with:
          publish-templates: true
          base-path-to-templates: ./src
          generate-docs: true

      - name: Generate README Pull Request
        run: |
          set -e

          # Configure git and Push updates
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config pull.rebase false

          branch="automated-documentation-update-${GITHUB_RUN_ID}"
          git checkout -b "$branch"
          message='Automated documentation update'

          # Add / update and commit
          find . -type f -name README.md -print0 | xargs -0 git add
          git commit -m 'Automated documentation update [skip ci]' || export NO_UPDATES=true

          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh pr create --title "$message" --body "$message"
          fi
