name: Test and Push Devcontainer Images

on:
  push:
    paths:
      - ".github/workflows/test-and-push.yaml"
      - "src/**"
      - "test/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v5

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            color:
              - './**/color/**'
            hello:
              - './**/hello/**'
            base:
              - './**/base/**'
            dev-common:
              - './**/dev-common/**'

  test:
    needs: [changes]
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.templates != '[]' }}
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.changes.outputs.templates) }}
    steps:
      - uses: actions/checkout@v5

      - name: Smoke test for '${{ matrix.templates }}'
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"

  push:
    needs: [changes, test]
    if: ${{ needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.changes.outputs.templates) }}
    steps:
      - uses: actions/checkout@v5

      - name: Push image for '${{ matrix.templates }}'
        uses: ./.github/actions/push-image
        with:
          template: "${{ matrix.templates }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
